---
# yamllint configuration for TB Coin Engine ML
# https://yamllint.readthedocs.io/

extends: default

rules:
  line-length:
    max: 120
    level: warning
  
  indentation:
    spaces: 2
    indent-sequences: true
  
  comments:
    min-spaces-from-content: 2
  
  document-start: disable
  
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']

ignore: |
  node_modules/
  .venv/
  venv/
  .github/workflows/*.yml
